# Linguagem Julia

In [1]:
?println

search: println printstyled print sprint isprint



```
println([io::IO], xs...)
```

Print (using [`print`](@ref)) `xs` to `io` followed by a newline. If `io` is not supplied, prints to the default output stream [`stdout`](@ref).

See also [`printstyled`](@ref) to add colors etc.

# Examples

```jldoctest
julia> println("Hello, world")
Hello, world

julia> io = IOBuffer();

julia> println(io, "Hello", ',', " world.")

julia> String(take!(io))
"Hello, world.\n"
```


In [13]:
VERSION

v"1.10.6"

In [8]:
# ; → executa uma função direto do sistema operacional
;pwd

C:\Users\david\Desktop\Formacao_Engenheiro_inteligencia_artificial\8-DS_e_ML_com_Julia\JuliaLanguage


# Variáveis

In [20]:
frase = "Introdução Linguagem JULIA"
nome = "David Francisco"
idade = 40
peso = 84.4

println(frase)
println(nome)
println(typeof(nome))
println(idade, " anos")
println(typeof(idade))
println(peso)
println(typeof(peso))

Introdução Linguagem JULIA
David Francisco
String
40 anos
Int64
84.4
Float64


# Operações Aritmeticas

In [23]:
#= 
Comentarios de 
varias linhas inicia
com hastag+igual
e termina com igual+hastag
=#
# Comentario simples - apenas hastag
n1 = 10
n2 = 5
soma = n1+n2
sub = n1-n2
mult = n1*n2
div = n1/n2
pot = n1^n2
modulo = n1%n2
println("A soma de ", n1, " e " ,n2, " é ", soma)
println("A subtração de ", n1, " por " ,n2, " é ", sub)
println("A multiplicação de ", n1, " por " ,n2, " é ", mult)
println("A divisão de ", n1, " por " ,n2, " é ", div)
println("A potencia de ", n1, " elevado " ,n2, " é ", pot)
println("O modulo de ", n1, " por " ,n2, " é ", modulo)

A soma de 10 e 5 é 15
A subtração de 10 por 5 é 5
A multiplicação de 10 por 5 é 50
A divisão de 10 por 5 é 2.0
A potencia de 10 elevado 5 é 100000
O modulo de 10 por 5 é 0


# String
- "String"
- 'a' → para apenas um caracter
- """Usado para destaque de "palavras" na frase"""

In [26]:
println(typeof("String"))
println(typeof('a' ))
println(typeof( """Usado para destaque de "palavras" na frase"""))

String
Char
String


# Interpolação

- usa $variavel dentro de aspas duplas

In [29]:
nome = "David Francisco"
idade = 45
peso = 84.4

print("Olá, Sr $nome, $idade anos, após a avaliação seu peso ideal é 77 kilos, você está com $peso, precisa baixar $(peso-77)")

Olá, Sr David Francisco, 45 anos, após a avaliação seu peso ideal é 77 kilos, você está com 84.4, precisa baixar 7.400000000000006

# Concatenação

- Separa com virgula → println("A soma de ", n1, " e " ,n2, " é ", soma)

In [ ]:
n1 = 10
n2 = 5
soma = n1+n2
sub = n1-n2
mult = n1*n2
div = n1/n2
pot = n1^n2
modulo = n1%n2
println("A soma de ", n1, " e " ,n2, " é ", soma)
println("A subtração de ", n1, " por " ,n2, " é ", sub)
println("A multiplicação de ", n1, " por " ,n2, " é ", mult)
println("A divisão de ", n1, " por " ,n2, " é ", div)
println("A potencia de ", n1, " elevado " ,n2, " é ", pot)
println("O modulo de ", n1, " por " ,n2, " é ", modulo)

# Estruturas de dados

### Tuplas - index em julia começa com 1
### São imutáveis

In [1]:
cores = ("Red","Green","Blue")

("Red", "Green", "Blue")

In [2]:
cores[1]

"Red"

#### Tuplas nomeadas

In [3]:
carros = (fusca = "1.5 gasolina 1979", audi = "2.0 Flex 2019", onix = "1.0 Flex 2015")

(fusca = "1.5 gasolina 1979", audi = "2.0 Flex 2019", onix = "1.0 Flex 2015")

In [6]:
carros.onix

"1.0 Flex 2015"

In [5]:
carros[1]

"1.5 gasolina 1979"

# Dicionários

In [9]:
contatos = Dict("David" => "17 99107-2558", "Fernanda" => "17 99108-5552", "Fulano" => "11 1111-1111")
contatos

Dict{String, String} with 3 entries:
  "David"    => "17 99107-2558"
  "Fernanda" => "17 99108-5552"
  "Fulano"   => "11 1111-1111"

In [10]:
contatos["Leticia"]="17 99120-5898"
contatos

Dict{String, String} with 4 entries:
  "Leticia"  => "17 99120-5898"
  "David"    => "17 99107-2558"
  "Fernanda" => "17 99108-5552"
  "Fulano"   => "11 1111-1111"

In [12]:
pop!(contatos, "Fulano")
contatos

Dict{String, String} with 3 entries:
  "Leticia"  => "17 99120-5898"
  "David"    => "17 99107-2558"
  "Fernanda" => "17 99108-5552"

# Arrays - Listas

In [13]:
funcionarios = ["func1","func2","func3","func4","func5"]
funcionarios

5-element Vector{String}:
 "func1"
 "func2"
 "func3"
 "func4"
 "func5"

In [14]:
funcionarios[5] = "Fernanda"

"Fernanda"

In [15]:
push!(funcionarios, "David")
funcionarios

6-element Vector{String}:
 "func1"
 "func2"
 "func3"
 "func4"
 "Fernanda"
 "David"

In [16]:
salarios = [1600,1600,1600,1600,3000,3000]

6-element Vector{Int64}:
 1600
 1600
 1600
 1600
 3000
 3000

In [17]:
maoObra = [funcionarios, salarios]
maoObra

2-element Vector{Vector}:
 ["func1", "func2", "func3", "func4", "Fernanda", "David"]
 [1600, 1600, 1600, 1600, 3000, 3000]

# Criando matrix com valores randomicos

In [18]:
matriz_4x3 = rand(4,3)

4×3 Matrix{Float64}:
 0.775332  0.348542  0.410014
 0.359636  0.80976   0.417823
 0.348112  0.749524  0.924246
 0.432184  0.756623  0.998874

In [19]:
#Cria duas matriz 4x3 
array_4x3x2 = rand(4,3,2)

4×3×2 Array{Float64, 3}:
[:, :, 1] =
 0.200473  0.34077   0.929039
 0.223862  0.437269  0.997693
 0.718695  0.252942  0.969085
 0.379423  0.254008  0.581331

[:, :, 2] =
 0.286     0.226903  0.803261
 0.199602  0.813446  0.63888
 0.249374  0.609482  0.792917
 0.396613  0.631928  0.801056